title: IntGalaxy Design
email: your.email@example.com
description: 极简风格平面设计作品集
baseurl: ""
url: "https://intgalaxy.top"

theme: jekyll-theme-minimal

# 作品集分类配置
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# 导航菜单配置
nav_links:
  - title: 首页
    url: /
  - title: 关于我
    url: /about/
  - title: 作品集
    url: /portfolio/
  - title: 博客
    url: /blog/
  - title: 联系方式
    url: /contact/

# 图片优化设置
image:
  default_path: /assets/images/
  portfolio_thumbnail: 600x400
  portfolio_full: 1200x800